// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0ATly6RLzFb_c7csHipmc7lakJfZf8fs',
    appId: '1:661887084801:web:7b503059b42e8620b31300',
    messagingSenderId: '661887084801',
    projectId: 'lasei-app-socios',
    authDomain: 'lasei-app-socios.firebaseapp.com',
    storageBucket: 'lasei-app-socios.appspot.com',
    measurementId: 'G-G0PDCBPG1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeXh30BIxqvIJe4oIp8Z_ymUTDyirYJ3k',
    appId: '1:661887084801:android:3d07fe2576662c3bb31300',
    messagingSenderId: '661887084801',
    projectId: 'lasei-app-socios',
    storageBucket: 'lasei-app-socios.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuxzoksbzGjsnd0hhnCQoPtS8YwbP9nNY',
    appId: '1:661887084801:ios:70e49d3421b5f8a5b31300',
    messagingSenderId: '661887084801',
    projectId: 'lasei-app-socios',
    storageBucket: 'lasei-app-socios.appspot.com',
    iosClientId: '661887084801-4vllf1pesmmaer369peab82rojpohc27.apps.googleusercontent.com',
    iosBundleId: 'com.example.lasei',
  );
}
